#!/bin/bash

apt-get -y --force-yes install nova-compute nova-network sysfsutils

cat << EOF > /etc/nova/nova.conf
[DEFAULT]
dhcpbridge_flagfile=/etc/nova/nova.conf
dhcpbridge=/usr/bin/nova-dhcpbridge
logdir=/var/log/nova
state_path=/var/lib/nova
lock_path=/var/lock/nova
force_dhcp_release=True
libvirt_use_virtio_for_bridges=True
verbose=True
ec2_private_dns_show_ip=True
api_paste_config=/etc/nova/api-paste.ini
enabled_apis=osapi_compute,metadata

auth_strategy = keystone
my_ip = AAA.BBB.CCC.DDD
rpc_backend = rabbit
verbose = True

# network conf
network_api_class = nova.network.api.API
security_group_api = nova
#firewall_driver = nova.virt.libvirt.firewall.IptablesFirewallDriver
network_manager = nova.network.manager.FlatDHCPManager
network_size = 254
allow_same_net_traffic = False
multi_host = False
multi_node = False
send_arp_for_ha = False
share_dhcp_address = True
force_dhcp_release = True
#flat_network_bridge = br100
#flat_interface = eth0
#public_interface = eth0 

[database]
connection = mysql+pymysql://nova:NOVA_DBPASS@CONTROLLER_HOSTNAME/nova

[oslo_messaging_rabbit]
rabbit_host = CONTROLLER_HOSTNAME
rabbit_userid = openstack
rabbit_password = RABBIT_PASS

[keystone_authtoken]
auth_uri = http://CONTROLLER_HOSTNAME:5000
auth_url = http://CONTROLLER_HOSTNAME:35357
auth_plugin = password
project_domain_id = default
user_domain_id = default
project_name = service
username = nova
password = NOVA_PASS

[oslo_concurrency]
lock_path = /var/lib/nova/tmp

[glance]
host = CONTROLLER_HOSTNAME
EOF

service nova-compute restart

rm -f /var/lib/nova/nova.sqlite
