#!/bin/bash

service nova-api stop
service nova-scheduler stop
service nova-conductor stop

echo 'DROP DATABASE nova;' | mysql -u root -proot

apt-get -y --force-yes purge nova-api nova-conductor nova-scheduler python-novaclient
