#!/bin/bash

echo 'CREATE DATABASE glance;' | mysql -u root -proot
echo "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' IDENTIFIED BY 'GLANCE_DBPASS';" |mysql -u root -proot
echo "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' IDENTIFIED BY 'GLANCE_DBPASS';" |mysql -u root -proot

. admin-openrc.sh

openstack user create --domain default --password GLANCE_PASS glance
openstack role add --project service --user glance admin
openstack service create --name glance \
    --description "OpenStack Image service" image

openstack endpoint create --region RegionOne \
      image public http://CONTROLLER_HOSTNAME:9292
openstack endpoint create --region RegionOne \
      image internal http://CONTROLLER_HOSTNAME:9292
openstack endpoint create --region RegionOne \
      image admin http://CONTROLLER_HOSTNAME:9292

apt-get -y --force-yes install glance python-glanceclient

cat << EOF > /etc/glance/glance-api.conf
[DEFAULT]
notification_driver = noop
verbose = True

[database]
connection = mysql+pymysql://glance:GLANCE_DBPASS@CONTROLLER_HOSTNAME/glance
backend = sqlalchemy
 
[keystone_authtoken]
auth_uri = http://CONTROLLER_HOSTNAME:5000
auth_url = http://CONTROLLER_HOSTNAME:35357
auth_plugin = password
project_domain_id = default
user_domain_id = default
project_name = service
username = glance
password = GLANCE_PASS

[paste_deploy]
flavor = keystone

[glance_store]
default_store = file
filesystem_store_datadir = /var/lib/glance/images/
EOF

cat << EOF > /etc/glance/glance-registry.conf
[DEFAULT]
notification_driver = noop
verbose = True
backend = sqlalchemy

[database]
connection = mysql+pymysql://glance:GLANCE_DBPASS@CONTROLLER_HOSTNAME/glance

[keystone_authtoken]
auth_uri = http://CONTROLLER_HOSTNAME:5000
auth_url = http://CONTROLLER_HOSTNAME:35357
auth_plugin = password
project_domain_id = default
user_domain_id = default
project_name = service
username = glance
password = GLANCE_PASS

[paste_deploy]
flavor = keystone
EOF

su -s /bin/sh -c "glance-manage db_sync" glance

service glance-registry restart
service glance-api restart

rm -f /var/lib/glance/glance.sqlite

echo "export OS_IMAGE_API_VERSION=2" | tee -a admin-openrc.sh demo-openrc.sh
source admin-openrc.sh
wget http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
glance image-create --name "cirros" --file cirros-0.3.4-x86_64-disk.img \
    --disk-format qcow2 --container-format bare --visibility public --progress \
    --id 48644096-5555-4835-99a0-59089dd7da1b
glance image-list
