#!/bin/bash
set -x

git clone https://github.com/openstack/nova-docker -b stable/mitaka
cd nova-docker
pip install .
cd -

rm -fr nova-docker

echo "[DEFAULT]" > /etc/nova/nova-compute.conf
echo "compute_driver=novadocker.virt.docker.DockerDriver" >> /etc/nova/nova-compute.conf

usermod -a -G docker nova

service nova-network restart
service nova-compute restart
