#!/bin/bash
set -x

if [ ! -d fpga-nova ]; then
    git clone -b dev https://github.com/intelsdi-x/fpga-nova
    if [ $? != 0 ]; then
        echo Failure in getting fpga-nova repository
        exit
    fi
fi

git clone https://github.com/openstack/nova-docker -b stable/mitaka

cd nova-docker
pip uninstall -y nova-docker
patch -Np1 -i ../fpga-nova/patches/nova_docker.patch
pip install .
cd -

echo "fpga_simulation_mode = False" >> /etc/nova/nova-compute.conf

service nova-network restart
service nova-compute restart
