#!/bin/bash
set -x

apt-get -y --force-yes install chrony
sed -i '/^server [0-9].debian.*/d' /etc/chrony/chrony.conf
echo 'server 172.28.168.170 offline minpoll 8' >> /etc/chrony/chrony.conf
apt-get -y --force-yes install software-properties-common
add-apt-repository -y cloud-archive:mitaka
apt-get update && apt-get -y --force-yes dist-upgrade
