#!/bin/bash
set -x

cat /etc/glance/glance-api.conf | awk '/\[DEFAULT\]/ { print; print "container_formats = ami,ari,aki,bare,ovf,ova,docker"; next }1' > glance-api.conf
mv -f glance-api.conf /etc/glance/glance-api.conf
restorecon -v /etc/glance/glance-api.conf
systemctl openstack-restart glance-api glance-registry

. admin-openrc.sh

docker pull busybox
docker save -o busyimg busybox
openstack image create --file busyimg --public --container-format docker \
    --disk-format raw --id 4ba11f84-9b8d-4bcd-8f28-74f8cedcb1dc busybox
rm -f busyimg
IMAGE_ID=$(openstack image list | grep busybox | awk '{print $2}')
if [ "${IMAGE_ID}x" == "x" ]; then
    echo "Cannot find busybox image"
    exit 1
fi
glance image-update --property os_command_line='/bin/sleep 100d' $IMAGE_ID
