#!/bin/bash
set -x

if [ ! -d fpga-nova ]; then
    git clone FPGA-NOVA-REPO
    if [ $? != 0 ]; then
        echo Failure in getting fpga-nova repository
        exit
    fi
fi

current=$(rpm -qi openstack-nova-common | grep '^Version' | tr -s ' ' | cut -d ' ' -f 3 )
[[ ! -e "fpga-nova/patches/rhel_72-nova-${current}.patch" ]] && echo "No patch for version ${current}!" && exit 1
fpga_dir=$(pwd)
cd /usr/lib/python2.7/site-packages
patch -Np1 -i "${fpga_dir}/fpga-nova/patches/rhel_72-nova-${current}.patch"
cd -
systemctl restart openstack-nova-compute
