#!/bin/bash
set -x

. admin-openrc.sh

su -s /bin/sh -c "nova-manage api_db sync" nova
su -s /bin/sh -c "nova-manage db sync" nova

systemctl enable openstack-nova-api openstack-nova-scheduler \
  openstack-nova-conductor
systemctl start openstack-nova-api openstack-nova-scheduler \
  openstack-nova-conductor
