#!/bin/bash
set -x

echo 'CREATE DATABASE keystone;' | mysql -u root -proot
echo "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY 'KEYSTONE_DBPASS';" |mysql -u root -proot
echo "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY 'KEYSTONE_DBPASS';" |mysql -u root -proot

yum install -y openstack-keystone httpd mod_wsgi

cat << EOF > /etc/keystone/keystone.conf
[DEFAULT]
log_dir = /var/log/keystone

[database]
connection = mysql+pymysql://keystone:KEYSTONE_DBPASS@CONTROLLER_HOSTNAME/keystone

[token]
provider = fernet
EOF

su -s /bin/sh -c "keystone-manage db_sync" keystone
keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
keystone-manage credential_setup --keystone-user keystone --keystone-group keystone

keystone-manage bootstrap --bootstrap-password ADMIN__OS_PASSWORD \
  --bootstrap-admin-url http://CONTROLLER_HOSTNAME:35357/v3/ \
  --bootstrap-internal-url http://CONTROLLER_HOSTNAME:35357/v3/ \
  --bootstrap-public-url http://CONTROLLER_HOSTNAME:5000/v3/ \
  --bootstrap-region-id RegionOne

echo ServerName CONTROLLER_HOSTNAME >> /etc/httpd/conf/httpd.conf
ln -s /usr/share/keystone/wsgi-keystone.conf /etc/httpd/conf.d/
systemctl enable httpd.service
systemctl start httpd.service

# create openrc scripts
cat << EOF > admin-openrc.sh
export OS_PROJECT_DOMAIN_NAME=ADMIN__OS_PROJECT_DOMAIN_NAME
export OS_USER_DOMAIN_NAME=ADMIN__OS_USER_DOMAIN_NAME
export OS_PROJECT_NAME=ADMIN__OS_PROJECT_NAME
export OS_USERNAME=ADMIN__OS_USERNAME
export OS_PASSWORD=ADMIN__OS_PASSWORD
export OS_AUTH_URL=http://CONTROLLER_HOSTNAME:35357/v3
export OS_IDENTITY_API_VERSION=ADMIN__OS_IDENTITY_API_VERSION
export OS_IMAGE_API_VERSION=ADMIN__OS_IMAGE_API_VERSION
EOF

cat << EOF > demo-openrc.sh
export OS_PROJECT_DOMAIN_NAME=DEMO__OS_PROJECT_DOMAIN_NAME
export OS_USER_DOMAIN_NAME=DEMO__OS_USER_DOMAIN_NAME
export OS_PROJECT_NAME=DEMO__OS_PROJECT_NAME
export OS_USERNAME=DEMO__OS_USERNAME
export OS_PASSWORD=DEMO__OS_PASSWORD
export OS_AUTH_URL=http://CONTROLLER_HOSTNAME:5000/v3
export OS_IDENTITY_API_VERSION=DEMO__OS_IDENTITY_API_VERSION
export OS_IMAGE_API_VERSION=DEMO__OS_IMAGE_API_VERSION
EOF

source admin-openrc.sh

openstack project create --domain default \
    --description "Service Project" service
openstack project create --domain default --description "Demo Project" demo
openstack user create --domain default --password demo demo
openstack role create user
openstack role add --project demo --user demo user

