#!/bin/bash
set -x

yum install -y openstack-nova-compute openstack-nova-network

cat << EOF > /etc/nova/nova.conf
[DEFAULT]
dhcpbridge_flagfile=/etc/nova/nova.conf
dhcpbridge=/usr/bin/nova-dhcpbridge
logdir=/var/log/nova
state_path=/var/lib/nova
lock_path=/var/lock/nova
force_dhcp_release=True
libvirt_use_virtio_for_bridges=True
verbose=True
debug=True
ec2_private_dns_show_ip=True
api_paste_config=/etc/nova/api-paste.ini
auth_strategy = keystone
my_ip = AAA.BBB.CCC.DDD
transport_url = rabbit://openstack:RABBIT_PASS@CONTROLLER_HOSTNAME
use_neutron = False
network_manager = nova.network.manager.FlatDHCPManager
network_size = 254
allow_same_net_traffic = False
multi_host = False
multi_node = False
send_arp_for_ha = False
share_dhcp_address = True
force_dhcp_release = True
enabled_apis = osapi_compute,metadata
firewall_driver = nova.virt.firewall.NoopFirewallDriver

[database]
connection = mysql+pymysql://nova:NOVA_DBPASS@CONTROLLER_HOSTNAME/nova

[keystone_authtoken]
auth_uri = http://CONTROLLER_HOSTNAME:5000
auth_url = http://CONTROLLER_HOSTNAME:35357
auth_type = password
project_domain_name = default
user_domain_name = default
project_name = service
username = nova
password = NOVA_PASS

[oslo_concurrency]
lock_path = /var/lib/nova/tmp

[glance]
api_servers = http://CONTROLLER_HOSTNAME:9292
EOF

systemctl enable openstack-nova-compute.service
