#!/bin/bash
set -x

cat /etc/nova/nova.conf | awk '/\[DEFAULT\]/ { print; print "scheduler_default_filters = RamFilter,ComputeFilter,AvailabilityZoneFilter,ImagePropertiesFilter,FpgaFilter"; next }1' > nova.conf
mv -f nova.conf /etc/nova/nova.conf
cat /etc/nova/nova.conf | awk '/\[DEFAULT\]/ { print; print "scheduler_available_filters = nova.scheduler.filters.fpga_filter.FpgaFilter"; next }1' > nova.conf
mv -f nova.conf /etc/nova/nova.conf
cat /etc/nova/nova.conf | awk '/\[DEFAULT\]/ { print; print "scheduler_available_filters = nova.scheduler.filters.all_filters"; next }1' > nova.conf
mv -f nova.conf /etc/nova/nova.conf
restorecon -v /etc/nova/nova.conf

systemctl restart openstack-nova-api openstack-nova-scheduler \
  openstack-nova-conductor
