#!/bin/bash
set -x

systemctl stop openstack-glance-registry openstack-glance-api
echo 'DROP DATABASE glance;' | mysql -u root -proot
yum remove -y openstack-glance openstack-python-glanceclient \
    python-glanceclient
